name       : light
version    : '1.2'
release    : 3
source     :
    - https://github.com/haikarainen/light/releases/download/v1.2/light-1.2.tar.gz : 6e35df7ad8ded77645b314c5928118c65d65c833a0a5cb26eade7943adccebaf
license    : GPL-3.0
component  : system.utils
summary    : GNU/Linux application to control backlights
description: |
    GNU/Linux application to control backlights
builddeps  :
    - help2man
setup      : |
    %configure --with-udev
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/share/doc
