name       : light
version    : 1.0
release    : 1
source     :
    - https://github.com/haikarainen/light/archive/v1.0.tar.gz : 974608ee42ffe85cfd23184306d56d86ec4e6f4b0518bafcb7b3330998b1af64
license    : GPL-3.0
component  : system.utils
summary    : GNU/Linux application to control backlights
description: |
    GNU/Linux application to control backlights
builddeps  :
    - help2man
build      : |
    %make
install    : |
    %make_install
    chmod 00755 $installdir/usr/bin/light
