name       : light
version    : 1.1.2
release    : 2
source     :
    - https://github.com/haikarainen/light/archive/1.1.2.tar.gz : 291ef234929adb20fe96359724c5ccad36cf396dd110f7001654c21e17800032
license    : GPL-3.0
component  : system.utils
summary    : GNU/Linux application to control backlights
description: |
    GNU/Linux application to control backlights
builddeps  :
    - help2man
build      : |
    %make
install    : |
    %make_install
    chmod 00755 $installdir/usr/bin/light
