name       : light
version    : 1.2.2
release    : 5
source     :
    - https://github.com/haikarainen/light/archive/v1.2.2.tar.gz : 62e889ee9be80fe808a972ef4981acc39e83a20f9a84a66a82cd1f623c868d9c
license    : GPL-3.0
component  : system.utils
summary    : GNU/Linux application to control backlights
description: |
    GNU/Linux application to control backlights
builddeps  :
    - help2man
setup      : |
    %patch -p1 < $pkgfiles/no-fcommon.patch
    %autogen --with-udev
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/share/doc
